IMPROVED build cache

diff --git a/image/debian/Dockerfile.debian b/image/debian/Dockerfile.debian
--- a/image/debian/Dockerfile.debian
+++ b/image/debian/Dockerfile.debian
@@ -4,7 +4,7 @@ FROM debian:stable-slim
 # The MOSAIC-Project - Debian Stable
 # __
 # Copyright (C) 2009 - 2026 Institute for Community Medicine
-# University Medicine of Greifswald - mosaic-project@uni-greifswald.de
+# University Medicine of Greifswald - kontakt-ths@med.uni-greifswald.de
 # __
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -21,8 +21,9 @@ FROM debian:stable-slim
 # ###license-information-end###
 
 # variables
-ARG DATE_YMD="20260204"
-ARG WAIT_FOR_IT_DOWNLOAD_URL="https://raw.githubusercontent.com/vishnubob/wait-for-it/ed77b63706ea721766a62ff22d3a251d8b4a6a30/wait-for-it.sh"
+ARG DATE_YMD="20260304"
+ARG WAIT_FOR_IT_FILE="wait-for-it.sh"
+ARG WAIT_FOR_IT_DOWNLOAD_URL="https://raw.githubusercontent.com/vishnubob/wait-for-it/ed77b63706ea721766a62ff22d3a251d8b4a6a30/${WAIT_FOR_IT_FILE}"
 ARG WAIT_FOR_IT_SHA256="2ea7475e07674e4f6c1093b4ad6b0d8cbbc6f9c65c73902fb70861aa66a6fbc0"
 
 ENV HOME="/opt/mosaic" \
@@ -47,11 +48,18 @@ LABEL org.opencontainers.image.authors="ronny.schuldt@uni-greifswald.de" \
 
 COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["scripts", "${HOME}"]
 COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["help-and-usage", "${ENTRY_USAGE}"]
-RUN cd ${HOME} && \
+COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["README.md", "${ENTRY_USAGE}/layer-readme/README-debian.md"]
+RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
+	--mount=type=cache,target=/var/lib/apt/lists,sharing=locked,id=apt-lists \
+	--mount=type=cache,target=/downloads,sharing=locked,id=downloads \
+    rm -f /etc/apt/apt.conf.d/docker-clean && \
+    echo -n "> 0. check cache: apt-cache ($(du -sh /var/cache/apt/archives/ | awk '{print $1}'), $(ls /var/cache/apt/archives | wc -w) files)" && \
+    echo ", downloads ($(du -sh /downloads/ | awk '{print $1}'), $(ls /downloads | wc -w) files)" && \
+    cd ${HOME} && \
     echo "> 1. install system-updates" && \
     apt-get update && apt-get upgrade -y && \
     \
-    echo "> 2. install missing packages (curl,procps)" && \
+    echo "> 2. install missing packages (curl,procps) " && \
     apt-get install -y curl procps && \
     \
     echo "> 3. create user and group" && \
@@ -61,9 +69,12 @@ RUN cd ${HOME} && \
     echo "> 4. create folders and permissions" && \
     mkdir -m 777 ${MOS_READY_PATH} ${MOS_TEMP_PATH} ${ENTRY_LOGS} && \
     \
-    echo "> 5. download wait-for-it-script" && \
-    (curl -Lfo wait-for-it.sh ${WAIT_FOR_IT_DOWNLOAD_URL} || (>&2 echo "curl -Lfo wait-for-it.sh ${WAIT_FOR_IT_DOWNLOAD_URL}\n" && exit 1)) && \
-    (sha256sum wait-for-it.sh | grep -q ${WAIT_FOR_IT_SHA256} > /dev/null || (>&2 echo "sha256sum failed $(sha256sum wait-for-it.sh)" && exit 1)) && \
+    echo -n "> 5. download wait-for-it-script" && \
+    cd /downloads && \
+	((test -f ${WAIT_FOR_IT_FILE} && echo e) || (echo d && curl -LfsSO ${WAIT_FOR_IT_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${WAIT_FOR_IT_DOWNLOAD_URL} \n" && exit 1)) && \
+	sha256sum ${WAIT_FOR_IT_FILE} | grep -q ${WAIT_FOR_IT_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${WAIT_FOR_IT_FILE})" && exit 1) && \
+    cp ${WAIT_FOR_IT_FILE} ${HOME}/${WAIT_FOR_IT_FILE} && \
+    cd ${HOME} && \
     \
     echo "> 6. register bash-scripts" && \
     ln -s ${HOME}/register.sh /usr/bin/register && \
@@ -82,12 +93,10 @@ RUN cd ${HOME} && \
       --add-entrypoint="ENTRY_LOGS:${ENTRY_LOGS}" && \
     \
     echo "> 8. cleanup" && \
-    apt-get clean && \
-    apt-get autoclean && \
     apt-get autoremove -y && \
     chown ${USER}:${USER} -R ${HOME} ${MOS_READY_PATH} ${MOS_TEMP_PATH} ${ENTRY_LOGS} ${ENTRY_USAGE} && \
     chmod 777 -R ${HOME} && chmod 444 -R ${HOME}/*.txt && \
-    rm -rf install.log ${MOS_TEMP_PATH}/* /var/lib/apt/lists/* /var/cache/apt/*
+    rm -rf install.log
 
 WORKDIR ${HOME}
 USER ${USER}
diff --git a/image/mysql/Dockerfile.mysql.8 b/image/mysql/Dockerfile.mysql.8
--- a/image/mysql/Dockerfile.mysql.8
+++ b/image/mysql/Dockerfile.mysql.8
@@ -1,11 +1,11 @@
 ARG TAG=mosaicgreifswald/debian:latest
-FROM ${TAG}
+FROM ${TAG} AS build
 
 # ###license-information-start###
 # The MOSAIC-Project - MySQL-Server
 # __
-# Copyright (C) 2009 - 2025 Institute for Community Medicine
-# University Medicine of Greifswald - mosaic-project@uni-greifswald.de
+# Copyright (C) 2009 - 2026 Institute for Community Medicine
+# University Medicine of Greifswald - kontakt-ths@med.uni-greifswald.de
 # __
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -22,13 +22,48 @@ FROM ${TAG}
 # ###license-information-end###
 
 # variables
-ARG DATE_YMD="20250722"
-ARG MYSQL_VERSION="8.4.6"
-ARG MYSQL_X86_64_DOWNLOAD_URL="https://cdn.mysql.com/Downloads/MySQL-8.4/mysql-${MYSQL_VERSION}-linux-glibc2.28-x86_64-minimal.tar.xz"
-ARG MYSQL_X86_64_SHA256="f284b17b9e038adbe77f0dd5fb11ed30262286b23a390b8b4e367abc3574c42e"
-ARG MYSQL_AARCH64_DOWNLOAD_URL="https://cdn.mysql.com/Downloads/MySQL-8.4/mysql-${MYSQL_VERSION}-linux-glibc2.28-aarch64.tar.xz"
-ARG MYSQL_AARCH64_SHA256="ab2c553ee4349a6bbe62325d4efcb427204e389264c4759ca32a92eae9aa2abc"
+ARG MYSQL_VERSION="8.4.9"
+ARG MYSQL_DOWNLOAD_URL="https://cdn.mysql.com/Downloads/MySQL-8.4"
+ARG MYSQL_X86_64_FILE="mysql-${MYSQL_VERSION}-linux-glibc2.28-x86_64-minimal.tar.xz"
+ARG MYSQL_X86_64_SHA256="d0142fc30e04bae7f15a46567238adf8956acccd35c5bca6e448322644536e3d"
+ARG MYSQL_AARCH64_FILE="mysql-${MYSQL_VERSION}-linux-glibc2.28-aarch64.tar.xz"
+ARG MYSQL_AARCH64_SHA256="497a4143d542b5b85ec7249016b0ff6ac6e7a855302a9822f667ca293d801aea"
 
+ENV MYSQL_HOME="${HOME}/mysql"
+
+# create image
+USER root
+COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["scripts", "${MOS_TEMP_PATH}"]
+COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["help-and-usage", "/help-and-usage/"]
+COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["README.md", "/help-and-usage/layer-readme/README-mysql.md"]
+RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
+	--mount=type=cache,target=/var/lib/apt/lists,sharing=locked,id=apt-lists \
+    --mount=type=cache,target=/downloads,sharing=locked,id=downloads \
+	echo -n "> 0. check cache: apt-cache ($(du -sh /var/cache/apt/archives/ | awk '{print $1}'), $(ls /var/cache/apt/archives | wc -w) files)" && \
+	echo ", downloads ($(du -sh /downloads/ | awk '{print $1}'), $(ls /downloads | wc -w) files)" && \
+    \
+    echo "> 1. install system-updates" && \
+    apt-get update && apt-get upgrade -y && \
+    \
+    echo "> 2. install xz-utils" && \
+    apt-get install -y xz-utils && \
+    \
+    echo -n "> 3. mysql-server " && \
+	cd /downloads && \
+    ARCH="$([ "$(uname -m)" = "x86_64" ] && echo "x86_64" || echo "aarch64")" && \
+    MYSQL_FILE="$([ "${ARCH}" = "x86_64" ] && echo "${MYSQL_X86_64_FILE}" || echo "${MYSQL_AARCH64_FILE}")" && \
+    MYSQL_SHA256="$([ "${ARCH}" = "x86_64" ] && echo "${MYSQL_X86_64_SHA256}" || echo "${MYSQL_AARCH64_SHA256}")" && \
+    ((test -f ${MYSQL_FILE} && echo e) || (echo d && curl -LfsSO ${MYSQL_DOWNLOAD_URL}/${MYSQL_FILE}) || (>&2 echo -e "\ncurl -LfsSO ${MYSQL_DOWNLOAD_URL}/${MYSQL_FILE}\n" && exit 1)) && \
+    (sha256sum ${MYSQL_FILE} | grep ${MYSQL_SHA256} > /dev/null || (>&2 echo "sha256sum(${ARCH}) failed $(sha256sum ${MYSQL_FILE})" && exit 1)) && \
+    tar xf ${MYSQL_FILE} && \
+    mv $(ls --color=never -d mysql*/ | sed -e 's-/$--') ${MYSQL_HOME} && \
+    mv -t ${MYSQL_HOME}/ ${MOS_TEMP_PATH}/*.sh ${MOS_TEMP_PATH}/*.cnf && \
+    echo "export LD_LIBRARY_PATH=/opt/mysql/lib:/lib:/lib64:/usr/lib" > ${MYSQL_HOME}/library_path.sh
+
+###########
+FROM ${TAG}
+
+ARG DATE_YMD="20260304"
 ENV MYSQL_HOME="${HOME}/mysql" \
     MYSQL_OPTS="" \
     MYSQL_ENABLE_UPDATE_SCANNER="false" \
@@ -51,29 +86,22 @@ LABEL org.opencontainers.image.authors="ronny.schuldt@uni-greifswald.de" \
 
 # create image
 USER root
-COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["scripts", "${MYSQL_HOME}"]
-COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["help-and-usage", "${ENTRY_USAGE}/"]
-RUN cd ${MOS_TEMP_PATH} && \
+COPY --from=build --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["${MYSQL_HOME}", "${MYSQL_HOME}"]
+COPY --from=build --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["/help-and-usage", "${ENTRY_USAGE}/"]
+
+RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
+	--mount=type=cache,target=/var/lib/apt/lists,sharing=locked,id=apt-lists \
+    echo "> 0. check cache: apt-cache ($(du -sh /var/cache/apt/archives/ | awk '{print $1}'), $(ls /var/cache/apt/archives | wc -w) files)" && \
+	\
     echo "> 1. install system-updates" && \
-    apt-get update && \
-    if [ "$(date +%F)" != "$(stat -c '%.10y' $(ls -t /var/lib/dpkg/info/*.list | head -n 1))" ]; then apt-get upgrade -y; fi && \
+    apt-get update && apt-get upgrade -y && \
     \
-    echo "> 2. install xz-utils, procps and libraries" && \
-    apt-get install -y xz-utils procps libaio1 libnuma1 libncurses5 && \
+    echo "> 2. install procps and libraries" && \
+    apt-get install -y procps libaio1t64 libnuma1 libncurses6 && \
     mkdir -m 777 ${ENTRY_MYSQL_DATADIR} ${ENTRY_MYSQL_SQLS} ${ENTRY_MYSQL_UPDATE_SQLS} ${ENTRY_MYSQL_SOCKET} ${ENTRY_LOGS}/mysql && \
-    \
-    echo "> 3. mysql-server" && \
-    ARCH="$([ "$(uname -m)" = "x86_64" ] && echo "x86_64" || echo "aarch64")" && \
-    MYSQL_DOWNLOAD_URL="$([ "${ARCH}" = "x86_64" ] && echo "${MYSQL_X86_64_DOWNLOAD_URL}" || echo "${MYSQL_AARCH64_DOWNLOAD_URL}")" && \
-    MYSQL_SHA256="$([ "${ARCH}" = "x86_64" ] && echo "${MYSQL_X86_64_SHA256}" || echo "${MYSQL_AARCH64_SHA256}")" && \
-    (curl -Lfo mysql.tar ${MYSQL_DOWNLOAD_URL} || (>&2 /bin/echo -e "\ncurl -Lfo mysql.tar ${MYSQL_DOWNLOAD_URL}\n" && exit 1)) && \
-    (sha256sum mysql.tar | grep ${MYSQL_SHA256} > /dev/null || (>&2 echo "sha256sum(${ARCH}) failed $(sha256sum mysql.tar)" && exit 1)) && \
-    tar xf mysql.tar && \
-    cp -R mysql-*/* ${MYSQL_HOME}/ && \
-    echo "export LD_LIBRARY_PATH=/opt/mysql/lib:/lib:/lib64:/usr/lib" > ${MYSQL_HOME}/library_path.sh && \
     echo "export PATH=${MYSQL_HOME}/bin:${PATH}" > /etc/profile.d/mysql.sh && \
     \
-    echo "> 4. register mysql" && \
+    echo "> 3. register mysql" && \
     register \
         --add-version="MySQL-Server:\$(${MYSQL_HOME}/bin/mysqld -V 2>/dev/null | sed -r 's/^.+Ver ([0-9\.]+) .+$/\1/' | cat)" \
         --add-entrypoint="ENTRY_MYSQL_DATADIR:${ENTRY_MYSQL_DATADIR}" \
@@ -85,19 +113,16 @@ RUN cd ${MOS_TEMP_PATH} && \
         --add-healthcheck-script="${MYSQL_HOME}/healthcheck_mysql.sh" \
         --add-process="mysql:10:service:${MYSQL_HOME}/run_mysql.sh:${MYSQL_HOME}/mysql_started.sh" && \
     \
-    echo "> 5. cleanup" && \
-    apt-get remove --purge --auto-remove -y xz-utils && \
-    apt-get clean && \
-    apt-get autoclean && \
+    echo "> 4. cleanup" && \
     apt-get autoremove -y && \
     ln -s ${MYSQL_HOME}/my.cnf ${ENTRY_MYSQL_MY_CNF} && \
     ln -s ${ENTRY_LOGS}/mysql ${ENTRY_MYSQL_LOGS} && \
     ln -s ${MYSQL_HOME}/bin/* /usr/bin/ && \
     ln -s /dev/stdout ${MYSQL_HOME}/stdout.log && \
+    ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/libaio.so.1 && \
     chown ${USER}:${USER} -R ${MYSQL_HOME} ${ENTRY_MYSQL_DATADIR} ${ENTRY_MYSQL_SQLS} ${ENTRY_MYSQL_UPDATE_SQLS} \
     	${ENTRY_MYSQL_SOCKET} ${ENTRY_MYSQL_MY_CNF} ${ENTRY_MYSQL_LOGS} ${ENTRY_USAGE} && \
-    chmod 777 ${MYSQL_HOME} && chmod 666 ${MYSQL_HOME}/my.cnf && chmod 755 -R ${MYSQL_HOME}/*.sh && \
-	rm -rf ${MOS_TEMP_PATH}/* /var/lib/apt/lists/* /var/cache/apt/*
+    chmod 777 ${MYSQL_HOME} && chmod 666 ${MYSQL_HOME}/my.cnf
 
 USER ${USER}
 
diff --git a/image/wildfly/Dockerfile.wildfly.38 b/image/wildfly/Dockerfile.wildfly.38
--- a/image/wildfly/Dockerfile.wildfly.38
+++ b/image/wildfly/Dockerfile.wildfly.38
@@ -5,7 +5,7 @@ FROM ${TAG} AS build
 # The MOSAIC-Project - WildFly with MySQL-Connector and Healthcheck
 # __
 # Copyright (C) 2009 - 2026 Institute for Community Medicine
-# University Medicine of Greifswald - mosaic-project@uni-greifswald.de
+# University Medicine of Greifswald - kontakt-ths@med.uni-greifswald.de
 # __
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -29,20 +29,20 @@ ARG WILDFLY_FILE="wildfly-${WILDFLY_VERSION}.tar.gz"
 ARG WILDFLY_DOWNLOAD_URL="https://github.com/wildfly/wildfly/releases/download/${WILDFLY_VERSION}/${WILDFLY_FILE}"
 ARG WILDFLY_SHA256="35bac69f742054734cc05263642adfc4e2073211ef635e9e8c812c6de6c3a907"
 
-ARG MYSQL_CONNECTOR_VERSION="9.6.0"
+ARG MYSQL_CONNECTOR_VERSION="9.7.0"
 ARG MYSQL_CONNECTOR_FILE="mysql-connector-j-${MYSQL_CONNECTOR_VERSION}.jar"
 ARG MYSQL_CONNECTOR_DOWNLOAD_URL="${MAVEN_REPOSITORY}/com/mysql/mysql-connector-j/${MYSQL_CONNECTOR_VERSION}/${MYSQL_CONNECTOR_FILE}"
-ARG MYSQL_CONNECTOR_SHA256="66df1d453789dc8cb759a7dc17f58646893bf28483f262328650f170472a6ead"
+ARG MYSQL_CONNECTOR_SHA256="0353648eaa1c91e0f4020c959abf756bc866ffd583df22ae6b6f6e0cbd43eb44"
 
-ARG MARIA_CONNECTOR_VERSION="3.5.7"
+ARG MARIA_CONNECTOR_VERSION="3.5.8"
 ARG MARIA_CONNECTOR_FILE="mariadb-java-client-${MARIA_CONNECTOR_VERSION}.jar"
 ARG MARIA_CONNECTOR_DOWNLOAD_URL="${MAVEN_REPOSITORY}/org/mariadb/jdbc/mariadb-java-client/${MARIA_CONNECTOR_VERSION}/${MARIA_CONNECTOR_FILE}"
-ARG MARIA_CONNECTOR_SHA256="07bb1229dc184f3313a5aef4c5a6b3207c8dbaa09db4a26814c936f004b4c526"
+ARG MARIA_CONNECTOR_SHA256="6127dc7858047b3d4482899139640b0e2ab2b8abdeb708cfb8c011117771cddf"
 
-ARG PSQL_CONNECTOR_VERSION="42.7.10"
+ARG PSQL_CONNECTOR_VERSION="42.7.11"
 ARG PSQL_CONNECTOR_FILE="postgresql-${PSQL_CONNECTOR_VERSION}.jar"
 ARG PSQL_CONNECTOR_DOWNLOAD_URL="${MAVEN_REPOSITORY}/org/postgresql/postgresql/${PSQL_CONNECTOR_VERSION}/${PSQL_CONNECTOR_FILE}"
-ARG PSQL_CONNECTOR_SHA256="cab1cd67cfa25c25de4348e532298028288a877ba01c77d1619fe45416193387"
+ARG PSQL_CONNECTOR_SHA256="1981b31d3993c58702783c1cddf10a34e48c1f413d70ff1cb6def0a143484647"
 
 ARG ECLIPSELINK_VERSION="4.0.9"
 ARG ECLIPSELINK_FILE="eclipselink-${ECLIPSELINK_VERSION}.jar"
@@ -63,50 +63,54 @@ USER root
 COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["scripts", "${MOS_TEMP_PATH}"]
 COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["help-and-usage", "/help-and-usage"]
 COPY --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["README.md", "/help-and-usage/layer-readme/README-wildfly.md"]
-RUN cd ${MOS_TEMP_PATH} && \
+RUN --mount=type=cache,target=/downloads,sharing=locked,id=downloads \
+	--mount=type=cache,target=/var/lib/apt/lists,sharing=locked,id=apt-lists \
+    echo "> 0. check cache: downloads ($(du -sh /downloads/ | awk '{print $1}'), $(ls /downloads | wc -w) files)" && \
+    cd /downloads && \
+    \
     echo -n "> 1. get mysql-connector " && \
 	((test -f ${MYSQL_CONNECTOR_FILE} && echo e) || (echo d && curl -LfsSO ${MYSQL_CONNECTOR_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${MYSQL_CONNECTOR_DOWNLOAD_URL} \n" && exit 1)) && \
-	sha256sum ${MYSQL_CONNECTOR_FILE} | grep -q ${MYSQL_CONNECTOR_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${MYSQL_CONNECTOR_FILE})" && exit 1)
-
-RUN cd ${MOS_TEMP_PATH} && \
+	sha256sum ${MYSQL_CONNECTOR_FILE} | grep -q ${MYSQL_CONNECTOR_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${MYSQL_CONNECTOR_FILE})" && exit 1) && \
+    cp ./${MYSQL_CONNECTOR_FILE} ${MOS_TEMP_PATH}/${MYSQL_CONNECTOR_FILE} && \
+	\
     echo -n "> 2. get mariadb-connector " && \
 	((test -f ${MARIA_CONNECTOR_FILE} && echo e) || (echo d && curl -LfsSO ${MARIA_CONNECTOR_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${MARIA_CONNECTOR_DOWNLOAD_URL} \n" && exit 1)) && \
-	sha256sum ${MARIA_CONNECTOR_FILE} | grep -q ${MARIA_CONNECTOR_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${MARIA_CONNECTOR_FILE})" && exit 1)
-
-RUN cd ${MOS_TEMP_PATH} && \
-    echo -n "> 3. get postgresql-connector " && \
+	sha256sum ${MARIA_CONNECTOR_FILE} | grep -q ${MARIA_CONNECTOR_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${MARIA_CONNECTOR_FILE})" && exit 1) && \
+	cp ./${MARIA_CONNECTOR_FILE} ${MOS_TEMP_PATH}/${MARIA_CONNECTOR_FILE} && \
+	\
+	echo -n "> 3. get postgresql-connector " && \
     ((test -f ${PSQL_CONNECTOR_FILE} && echo e) || (echo d && curl -LfsSO ${PSQL_CONNECTOR_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${PSQL_CONNECTOR_DOWNLOAD_URL} \n" && exit 1)) && \
-	sha256sum ${PSQL_CONNECTOR_FILE} | grep -q ${PSQL_CONNECTOR_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${PSQL_CONNECTOR_FILE})" && exit 1)
-
-RUN cd ${MOS_TEMP_PATH} && \
+	sha256sum ${PSQL_CONNECTOR_FILE} | grep -q ${PSQL_CONNECTOR_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${PSQL_CONNECTOR_FILE})" && exit 1) && \
+	cp ./${PSQL_CONNECTOR_FILE} ${MOS_TEMP_PATH}/${PSQL_CONNECTOR_FILE} && \
+	\
     echo -n "> 4. get eclipselink " && \
     ((test -f ${ECLIPSELINK_FILE} && echo e) || (echo d && curl -LfsSO ${ECLIPSELINK_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${ECLIPSELINK_DOWNLOAD_URL} \n" && exit 1)) && \
-	sha256sum ${ECLIPSELINK_FILE} | grep -q ${ECLIPSELINK_SHA256} || (>&2 echo "sha256sum failed $(sha256sum ${ECLIPSELINK_FILE})" && exit 1)
-
-RUN cd ${MOS_TEMP_PATH} && \
-    echo -n "> 5. get eclipse.persistence.json " && \
-    ((test -f ${ECLIPSEJSON_FILE} && echo e) || (echo d && curl -LfsSO ${ECLIPSEJSON_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${ECLIPSEJSON_DOWNLOAD_URL} \n" && exit 1)) && \
-	sha256sum ${ECLIPSEJSON_FILE} | grep -q ${ECLIPSEJSON_SHA256} || (>&2 echo "sha256sum failed $(sha256sum ${ECLIPSEJSON_FILE})" && exit 1)
-
-RUN cd ${MOS_TEMP_PATH} && \
-    echo -n "> 6. get eclipse.persistence.core " && \
+	sha256sum ${ECLIPSELINK_FILE} | grep -q ${ECLIPSELINK_SHA256} || (>&2 echo "sha256sum failed $(sha256sum ${ECLIPSELINK_FILE})" && exit 1) && \
+	cp ./${ECLIPSELINK_FILE} ${MOS_TEMP_PATH}/${ECLIPSELINK_FILE} && \
+	\
+	echo -n "> 5. get eclipse.persistence.json " && \
+	((test -f ${ECLIPSEJSON_FILE} && echo e) || (echo d && curl -LfsSO ${ECLIPSEJSON_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${ECLIPSEJSON_DOWNLOAD_URL} \n" && exit 1)) && \
+	sha256sum ${ECLIPSEJSON_FILE} | grep -q ${ECLIPSEJSON_SHA256} || (>&2 echo "sha256sum failed $(sha256sum ${ECLIPSEJSON_FILE})" && exit 1) && \
+	cp ./${ECLIPSEJSON_FILE} ${MOS_TEMP_PATH}/${ECLIPSEJSON_FILE} && \
+	\
+	echo -n "> 6. get eclipse.persistence.core " && \
 	((test -f ${ECLIPSECORE_FILE} && echo e) || (echo d && curl -LfsSO ${ECLIPSECORE_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${ECLIPSECORE_DOWNLOAD_URL} \n" && exit 1)) && \
-	sha256sum ${ECLIPSECORE_FILE} | grep -q ${ECLIPSECORE_SHA256} || (>&2 echo "sha256sum failed $(sha256sum ${ECLIPSECORE_FILE})" && exit 1)
-
-RUN cd ${MOS_TEMP_PATH} && \
-    echo -n "> 7. install wildfly " && \
+	sha256sum ${ECLIPSECORE_FILE} | grep -q ${ECLIPSECORE_SHA256} || (>&2 echo "sha256sum failed $(sha256sum ${ECLIPSECORE_FILE})" && exit 1) && \
+	cp ./${ECLIPSECORE_FILE} ${MOS_TEMP_PATH}/${ECLIPSECORE_FILE} && \
+	\
+	echo -n "> 7. install wildfly " && \
 	((test -f ${WILDFLY_FILE} && echo e) || (echo d && curl -LfsSO ${WILDFLY_DOWNLOAD_URL}) || (>&2 echo -e "\ncurl -LfsSO ${WILDFLY_DOWNLOAD_URL} \n" && exit 1)) && \
 	(sha256sum ${WILDFLY_FILE} | grep -q ${WILDFLY_SHA256} || (>&2 echo -e "\nsha256sum failed $(sha256sum ${WILDFLY_FILE})" && exit 1)) && \
 	tar xf ${WILDFLY_FILE} && \
 	mv wildfly-${WILDFLY_VERSION} ${WILDFLY_HOME} && \
-    mv -t ${WILDFLY_HOME}/ ./*.sh ./internal_cli && \
+    mv -t ${WILDFLY_HOME}/ ${MOS_TEMP_PATH}/*.sh ${MOS_TEMP_PATH}/internal_cli && \
 	#rm -rf ${WILDFLY_HOME}/bin/*.bat ${WILDFLY_HOME}/bin/*.ps1 ${WILDFLY_HOME}/docs && \
 	mkdir -pm 777 ${WILDFLY_HOME}/standalone/log && touch ${WILDFLY_HOME}/standalone/log/server.log
 
 RUN echo "> 8. start wildfly" && \
     (${WILDFLY_HOME}/bin/standalone.sh &) && \
     START=$(date +%s) && \
-    TIMEOUT=120 && \
+    TIMEOUT=240 && \
     (until `/bin/bash ${WILDFLY_HOME}/wildfly_started.sh`;do sleep 1;SEC=$(($(date +%s)-START));if [ ${SEC} -ge $TIMEOUT ];then >&2 echo "starting-timeout (TIMEOUT=${TIMEOUT})";exit 1;fi;done) && \
     echo "> 9. prepare wildfly" && \
     ($JBOSS_CLI --connect --commands=" \
@@ -127,7 +131,8 @@ RUN echo "> 8. start wildfly" && \
         /subsystem=logging/pattern-formatter=DATE_DETAILED:add(pattern=\"%d %-5p %-4L [%c] (%t) %s%E%n\"), \
         /subsystem=logging/pattern-formatter=DATE_COMPACT:add(pattern=\"%d %-5.5p %-4.4L %-40.40c{2.} | %m%n\"), \
         /subsystem=logging/pattern-formatter=NO_DATE_DETAILED:add(pattern=\"%d{HH:mm:ss,SSS} %-5p %-4L [%c] (%t) %s%E%n\"), \
-        /subsystem=logging/pattern-formatter=NO_DATE_COMPACT:add(pattern=\"%d{HH:mm:ss,SSS} %-5.5p %-4.4L %-40.40c{2.} | %m%n\")" || exit 1) && \
+        /subsystem=logging/pattern-formatter=NO_DATE_COMPACT:add(pattern=\"%d{HH:mm:ss,SSS} %-5.5p %-4.4L %-40.40c{2.} | %m%n\"), \
+		/subsystem=logging/custom-handler=system-file-handler:add(class=org.jboss.logmanager.handlers.PeriodicSizeRotatingFileHandler, module=org.jboss.logmanager, named-formatter=DATE_COMPACT, properties={rotateSize=10240000,maxBackupIndex=20,append=true,suffix=\".yyyy-MM-dd\",fileName=\"\${jboss.server.log.dir}/system/system.log\"})" || exit 1) && \
     cp ${WILDFLY_HOME}/standalone/configuration/standalone.xml ${WILDFLY_HOME}/standalone/configuration/standalone_xml_history/standalone.${USER}.xml && \
     ($JBOSS_CLI --connect --commands=" \
         /subsystem=deployment-scanner/scanner=default:write-attribute(name=scan-enabled,value=false), \
@@ -150,7 +155,7 @@ RUN echo "> 11. cleanup" && \
 ###########
 FROM ${TAG}
 
-ARG DATE_YMD="20260304"
+ARG DATE_YMD="20260429"
 ENV WILDFLY_HOME="${HOME}/wildfly" \
     JBOSS_CLI="${HOME}/wildfly/bin/jboss-cli.sh" \
     LAUNCH_JBOSS_IN_BACKGROUND="true" \
@@ -184,11 +189,12 @@ USER root
 COPY --from=build --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["${WILDFLY_HOME}", "${WILDFLY_HOME}"]
 COPY --from=build --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=777 ["${HOME}/versions.sh", "${HOME}"]
 COPY --from=build --chown=${MOSAIC_UID}:${MOSAIC_GID} --chmod=555 ["/help-and-usage", "${ENTRY_USAGE}/"]
-RUN cd ${MOS_TEMP_PATH} && \
+RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
+	--mount=type=cache,target=/var/lib/apt/lists,sharing=locked,id=apt-lists \
+    echo "> 0. check cache: apt-cache ($(du -sh /var/cache/apt/archives/ | awk '{print $1}'), $(ls /var/cache/apt/archives | wc -w) files)" && \
+	cd ${MOS_TEMP_PATH} && \
     echo "> 1. install system-updates" && \
-    if [ "$(date +%F)" != "$(stat -c '%.10y' $(ls -t /var/lib/dpkg/info/*.list | head -n 1))" ]; then \
-		apt-get update && apt-get upgrade -y; \
-	fi && \
+    apt-get update && apt-get upgrade -y && \
     \
     echo "> 2. create folders and permissions" && \
     mkdir -m 777 ${ENTRY_WILDFLY_CLI} ${ENTRY_WILDFLY_DEPLOYS} ${ENTRY_LOGS}/wildfly && \
@@ -207,13 +213,11 @@ RUN cd ${MOS_TEMP_PATH} && \
       --add-process="wildfly:20:service:${WILDFLY_HOME}/run_wildfly.sh:${WILDFLY_HOME}/wildfly_started.sh" && \
     \
     echo "> 4. cleanup" && \
-    apt-get clean && \
-    apt-get autoclean && \
     apt-get autoremove -y && \
     ln -s ${WILDFLY_HOME}/standalone/data/addins ${ENTRY_WILDFLY_ADDINS} && \
     chown ${USER}:${USER} -R ${HOME} ${ENTRY_LOGS} ${ENTRY_WILDFLY_ADDINS} ${ENTRY_WILDFLY_LOGS} ${ENTRY_USAGE} && \
     chmod 777 -R ${HOME} ${ENTRY_LOGS} ${ENTRY_WILDFLY_LOGS} && \
-    rm -rf ${MOS_TEMP_PATH}/* /var/lib/apt/lists/* /var/cache/apt/*
+    rm -rf ${MOS_TEMP_PATH}/*
 
 USER ${USER}
 
